version: '3.3'
services:
  web:
    build: .
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/.ssh:/home/ubuntu/.ssh
    environment:
      JENKINS_ADMIN_ID: admin
      JENKINS_ADMIN_PASSWORD: ngomyquynh
      DOCKERHUB_ID: s3836322
      DOCKERHUB_PASSWORD: dckr_pat_OVW-BESNVfTEbSv9KhJ23v1nz5E